In [1]:
import pandas as pd

## Read data from file

In [2]:
#read data 
df = pd.read_csv('adult.data.csv')
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [3]:
df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')>

## How many of each race are represented in this dataset? This should be a Pandas series with race names as the index labels.

In [4]:
race_count = df['race'].value_counts()
race_count

White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: race, dtype: int64

In [5]:
df.race.unique()

array(['White', 'Black', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo',
       'Other'], dtype=object)

In [6]:
new_df=df['race'].value_counts()

In [7]:
pd.DataFrame(new_df)

                     race
White               27816
Black                3124
Asian-Pac-Islander   1039
Amer-Indian-Eskimo    311
Other                 271

# What is the average age of men?

In [8]:
average_age_men = df['age'][df['sex'] == 'Male'].mean()
average_age_men = round(average_age_men,1)
average_age_men

39.4

# What is the percentage of people who have a Bachelor's degree?

In [9]:
o

16.4

## What percentage of people with advanced education (`Bachelors`, `Masters`, or `Doctorate`) make more than 50K?

In [10]:
filter1 = (df['education'] == 'Bachelors' )&(df['salary'] == '>50K')
filter2 = (df['education'] == 'Masters' )&(df['salary'] == '>50K')
filter3 = (df['education'] == 'Doctorate' )&(df['salary'] == '>50K')

In [11]:
higher_education=df[(df['education']== 'Bachelors')|(df['education']== 'Masters')|(df['education']== 'Doctorate')]
higher_education

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K

In [17]:
my_results = df[(filter1)|(filter2)|(filter3)]
my_result = len(my_results) / len(higher_education)
round(my_result*100,1)

46.5

## with and without `Bachelors`, `Masters`, or `Doctorate`

In [13]:
higher_education=df[(df['education']== 'Bachelors')|(df['education']== 'Masters')|(df['education']== 'Doctorate')]
higher_education.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K

In [14]:
lower_education=df[(df['education']!= 'Bachelors')&(df['education']!= 'Masters')&(df['education']!= 'Doctorate')]
lower_education.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K

## percentage with salary >50K

#### HIGHER EDUCATION RICH PERCENTAGE

In [16]:
higher_education_rich = higher_education[higher_education['salary'] == '>50K']
higher_education_rich

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K

In [25]:
round((len(higher_education_rich) / len(higher_education))*100 ,1)

46.5

#### LOWER EDUCATION RICH PERCENTAGE

In [28]:
lower_education_rich = lower_education[lower_education['salary'] == '>50K']
lower_education_rich

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
38,31,Private,84154,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,38,?,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32518,57,Local-gov,110417,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,99999,0,40,United-States,>50K
32519,46,Private,364548,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,48,United-States,>50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [29]:
round((len(lower_education_rich) / len(lower_education))*100 ,1)

17.4

## What is the minimum number of hours a person works per week (hours-per-week feature)?

In [31]:
min_work_hours = None

In [32]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [65]:
min_work_hours = df['hours-per-week'].min()
min_work_hours

1

 ## What percentage of the people who work the minimum number of hours per week have a salary of >50K?

In [203]:
df['hours-per-week'].min()

1

In [205]:
min_worktime = df['hours-per-week'] == 1
my_frame = df[min_worktime]
len(my_frame)

20

In [84]:
a = len(my_frame[my_frame['salary'] == '>50K'])

In [207]:
b = len(my_frame[my_frame['salary'] == '<=50K'])

In [210]:
round((a / len(my_frame) )*100,2)

10.0

In [87]:
num_min_workers = len(df[min_worktime])
num_min_workers

20

In [88]:
rich_percentage = None

## What country has the highest percentage of people that earn >50K?

## highest_earning_country

In [112]:
highest_earning_country = None

In [146]:
#filters
salary_big = df['salary'] == '>50K'
salary_small = df['salary'] == '<=50K'

In [148]:
df['native-country'][salary_big].value_counts()

United-States         7171
?                      146
Philippines             61
Germany                 44
India                   40
Canada                  39
Mexico                  33
England                 30
Cuba                    25
Italy                   25
Japan                   24
Taiwan                  20
China                   20
Iran                    18
South                   16
Puerto-Rico             12
Poland                  12
France                  12
Jamaica                 10
El-Salvador              9
Greece                   8
Cambodia                 7
Yugoslavia               6
Hong                     6
Vietnam                  5
Ireland                  5
Ecuador                  4
Portugal                 4
Haiti                    4
Hungary                  3
Thailand                 3
Scotland                 3
Guatemala                3
Nicaragua                2
Peru                     2
Columbia                 2
Trinadad&Tobago          2
Dominican-Republic       2
Laos                     2
Honduras                 1
Name: native-country, dtype: int64

In [149]:
df['native-country'][salary_small].value_counts()

United-States                 21999
Mexico                          610
?                               437
Philippines                     137
Puerto-Rico                     102
El-Salvador                      97
Germany                          93
Canada                           82
Jamaica                          71
Cuba                             70
Dominican-Republic               68
South                            64
Vietnam                          62
Guatemala                        61
England                          60
India                            60
Columbia                         57
China                            55
Italy                            48
Poland                           48
Haiti                            40
Japan                            38
Portugal                         33
Nicaragua                        32
Taiwan                           31
Peru                             29
Iran                             25
Ecuador                          24
Greece                           21
Ireland                          19
France                           17
Trinadad&Tobago                  17
Laos                             16
Thailand                         15
Hong                             14
Outlying-US(Guam-USVI-etc)       14
Honduras                         12
Cambodia                         12
Yugoslavia                       10
Hungary                          10
Scotland                          9
Holand-Netherlands                1
Name: native-country, dtype: int64

In [151]:
new = pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [163]:
new['big']  = df['native-country'][salary_big].value_counts()
new['small'] = df['native-country'][salary_small].value_counts()
new['total'] = new['big']  + new['small']
new['rich'] = new['big'] / new['total']
new.sort_values(by='rich',ascending=False).head(10)

            big  small  total      rich
Iran         18     25     43  0.418605
France       12     17     29  0.413793
India        40     60    100  0.400000
Taiwan       20     31     51  0.392157
Japan        24     38     62  0.387097
Yugoslavia    6     10     16  0.375000
Cambodia      7     12     19  0.368421
Italy        25     48     73  0.342466
England      30     60     90  0.333333
Canada       39     82    121  0.322314

In [173]:
new.loc[new['rich'] == new['rich'].max()].index.values
print(new.loc[new['rich'] == new['rich'].max()].index.values[0])

Iran

In [145]:
df['salary'].unique()

array(['<=50K', '>50K'], dtype=object)

## highest_earning_country_percentage

In [175]:
highest_earning_country_percentage = round(new['rich'].max() * 100 ,1)
highest_earning_country_percentage

41.9

## Identify the most popular occupation for those who earn >50K in India.

In [198]:
top_IN_occupation = popular_in_india[popular_in_india['occupation'] == popular_in_india['occupation'].max()].index.values[0]

In [199]:
india = df['native-country'] == 'India'
popular_in_india = pd.DataFrame(df[india]['occupation'].value_counts())
df[india]['occupation'].value_counts()

Prof-specialty       40
Sales                14
Adm-clerical         11
Exec-managerial      10
Craft-repair          5
Tech-support          5
Protective-serv       4
Other-service         4
Handlers-cleaners     3
Machine-op-inspct     2
Transport-moving      2
Name: occupation, dtype: int64

In [200]:
popular_in_india[popular_in_india['occupation'] == popular_in_india['occupation'].max()].index.values[0]

'Prof-specialty'